---
language: ruby
branches:
  only:
    - master
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_GEM_VERSION="~> 4.0.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.1.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.2.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.3.0" STRICT_VARIABLES=yes
matrix:
  fast_finish: true
  allow_failures:
  - env: PUPPET_GEM_VERSION="~> 4.0.0" STRICT_VARIABLES=yes
  - env: PUPPET_GEM_VERSION="~> 4.1.0" STRICT_VARIABLES=yes
  exclude:
  # Ruby 2.1.0
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.2.0"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.3.0"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.4.0"
